version: '3.3'
services:
  web: 
    build: 
      context: .
      labels:
        - project = "TheRoyalTouch"               # Addinng MetaData to Image
    image: project_1:1.0.0.0                        # Custom Image Name
    container_name: project_1                       # Custom Container Name
    ports:                                          # Port Mapping
      - "82:80"
      - "5000:80"          
    
