version: '3.3'

services:

  web: 

    build: 

      context: .

      labels:
        - project = "The Royal Touch"               # Addinng MetaData to Image

      # dockerfile: Dockerfile                      // If Multiple Dockerfile Exist Then Specify Name Of Dockerfile

    image: project_1:1.0.0.0                        # Custom Image Name

    container_name: project_1                       # Custom Container Name

    ports:                                          # Port Mapping
      - "82:80"
      - "5000:80"          

    # volumes:                                        # Specified Volume If Any Changes Done In File Then It Will Automatic Reflect 
    #   - .:/var/www/html
    
